# Generated by Django 4.2.23 on 2025-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
