# Generated by Django 4.2.23 on 2025-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_remove_leaderboardentry_realise_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='score',
            field=models.TimeField(),
        ),
    ]
