# Generated by Django 4.2.23 on 2025-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_leaderboardentry_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='score',
            field=models.DateTimeField(),
        ),
    ]
